import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import ProviderLayout from "@/components/ProviderLayout";
import AuthLayout from "@/components/AuthLayout";

import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Treatment support',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ProviderLayout>
            <AuthLayout>
                {children}
            </AuthLayout>
        </ProviderLayout>
        </body>
        </html>
    )
}
